name: qc_pos_system
description: Pont of Sales system made with flutter desktop, MongoDb

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  window_manager: ^0.3.2
  fluent_ui: ^4.6.1
  flutter_riverpod: ^2.3.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl:
  image_picker_windows: ^0.1.0+6
  image_picker: ^0.8.7+5
  font_awesome_flutter: ^10.4.0
  mongo_dart: ^0.9.1
  flutter_smart_dialog: ^4.9.0+6
  google_fonts: ^4.0.4
  responsive_table:
    git:
      url: https://github.com/Emmanuelfrimpong/flutter_responsive_table.git


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true


  assets:
    - assets/images/